import Link from "next/link"

export const metadata = {
  title: 'Product Page of NextJS',
  description: 'Generated by create next app',
}

export default function Products() {
  return (
    <>
      Products
      <Link href='products/3' >Link of 3</Link> 
    </>
  )
}
